import test from 'node:test';import assert from 'node:assert/strict';
import {createFigmaMock,executeGenerated} from './helpers/figma-mock.mjs';
const api=await import('../src/resolve-resource-keys.mjs').catch(()=>({}));
function fixture(){const m=createFigmaMock();m.figma.fileKey='target';m.variable={id:'opaque-var',key:'a'.repeat(40),resolvedType:'STRING',variableCollectionId:'collection'};m.component={id:'1:1364',type:'COMPONENT',key:'b'.repeat(40),getPluginData:()=> 'guide/semantic-only'};m.figma.variables.getVariableByIdAsync=async()=>m.variable;m.figma.variables.getVariableCollectionByIdAsync=async()=>({id:'collection',key:'c'.repeat(40)});m.figma.getNodeByIdAsync=async()=>m.component;m.input={fileKey:'target',variableIds:['opaque-var'],nodeIds:['1:1364']};return m;}
const run=m=>executeGenerated(m.figma,api.buildResolveResourceKeysCode(m.input));
test('verified opaque IDs resolve real library keys separately from semantic keys without mutation',async()=>{const m=fixture(),result=await run(m);assert.equal(result.complete,true);assert.equal(result.variables[0].key,'a'.repeat(40));assert.equal(result.nodes[0].key,'b'.repeat(40));assert.equal(result.nodes[0].semanticKey,'guide/semantic-only');assert.deepEqual(result.coverage,{requested:2,verified:2,unresolved:[]});assert.equal(m.writes.length,0);});
test('bounded exact-ID schema rejects duplicates, empty requests and unknown options',()=>{for(const bad of [{fileKey:'target'}, {...fixture().input,variableIds:['x','x']},{...fixture().input,nodeIds:Array(101).fill('x')},{...fixture().input,script:'write()'}])assert.equal(api.resolveResourceKeysSchema.safeParse(bad).success,false);});
test('missing and mismatched objects remain unresolved without parsing keys from IDs',async()=>{for(const change of [m=>m.variable=null,m=>m.variable.id='wrong',m=>m.variable.key='bad',m=>m.component.type='FRAME',m=>m.component.id='wrong',m=>m.component.key=null]){const m=fixture();change(m);const result=await run(m);assert.equal(result.complete,false);assert.equal(result.coverage.unresolved.length,1);assert.equal(m.writes.length,0);}});
test('wrong target and switched file reject read proof',async()=>{const m=fixture();m.input.fileKey='other';await assert.rejects(run(m),/target|целев/);const n=fixture();n.figma.variables.getVariableByIdAsync=async()=>{n.figma.fileKey='other';return n.variable;};await assert.rejects(run(n),/target|целев/);});
