import {createHash,randomUUID,randomBytes,timingSafeEqual} from 'node:crypto';
import {mkdirSync,readFileSync,writeFileSync,renameSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
export const canonical = value => JSON.stringify(sort(value));
function sort(v){return Array.isArray(v)?v.map(sort):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])])):v;}
export const importArgsHash = input => createHash('sha256').update(canonical({fileKey:input.fileKey,variables:input.variables})).digest('hex');
export const operationArgsHash = input => createHash('sha256').update(canonical({fileKey:input.fileKey,name:input.name,args:input.args})).digest('hex');
const failure=(code,message,extra={})=>Object.assign(Error(message),{code,operationStatus:'not_applied',commandSent:false,...extra});
export class OperationJournal {
 constructor(directory){this.directory=join(directory,'operations');mkdirSync(this.directory,{recursive:true,mode:0o700});this.records=new Map();for(const f of readdirSync(this.directory).filter(f=>/^[a-f0-9-]{36}\.json$/i.test(f))){const r=JSON.parse(readFileSync(join(this.directory,f),'utf8'));this.records.set(r.operationId,r);}}
 save(r){r.updatedAt=new Date().toISOString();const p=join(this.directory,r.operationId+'.json'),tmp=p+'.tmp';writeFileSync(tmp,JSON.stringify(r),{mode:0o600});renameSync(tmp,p);this.records.set(r.operationId,r);return r;}
 get(fileKey,id){const r=this.records.get(id);if(!r)throw failure('OPERATION_NOT_FOUND','Операция не найдена',{operationId:id});if(r.fileKey!==fileKey)throw failure('OPERATION_TARGET_MISMATCH','Назначение операции не совпадает',{operationId:id});const {resumeTokenHash,lastConnectionId,...publicRecord}=r;return structuredClone(publicRecord);}
 begin(input,connectionId,resumeToken=randomBytes(32).toString('hex')){const operationId=input.operationId||randomUUID();if(!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(operationId))throw failure('INVALID_ARGUMENTS','Неверный operationId');const variableImport=Array.isArray(input.variables);const name=input.name||(variableImport?'import_variables':null);if(!name)throw failure('INVALID_ARGUMENTS','Не указано имя операции');const argsHash=variableImport?importArgsHash(input):operationArgsHash(input);if(this.records.has(operationId)){const r=this.get(input.fileKey,operationId);if(r.argsHash!==argsHash)throw failure('OPERATION_ARGUMENTS_MISMATCH','Аргументы операции изменились',{operationId});throw failure('OPERATION_ALREADY_EXISTS','Операция уже существует; прочитайте её журнал',{operationId});}for(const r of this.records.values())if(r.fileKey===input.fileKey&&!r.settled)throw failure('OPERATION_IN_PROGRESS','Операция записи уже выполняется',{operationId:r.operationId});return this.save({schemaVersion:2,resumeTokenHash:createHash('sha256').update(resumeToken).digest('hex'),operationId,fileKey:input.fileKey,name,argsHash,attempt:input.attempt||1,connectionId,stage:'dispatch',state:'pending',settled:false,commandSent:false,...(variableImport?{variables:structuredClone(input.variables)}:{operationInput:structuredClone(input.args)}),createdAt:new Date().toISOString(),sequence:0});}
 authorized(connectionId,e){const r=this.records.get(e?.operationId);if(!r||r.fileKey!==e.fileKey||r.argsHash!==e.argsHash)return false;if(connectionId===r.connectionId||connectionId===r.lastConnectionId)return true;if(typeof e.resumeToken!=='string'||!r.resumeTokenHash)return false;const actual=createHash('sha256').update(e.resumeToken).digest();return timingSafeEqual(actual,Buffer.from(r.resumeTokenHash,'hex'));}
 acknowledged(connectionId,e){const r=this.records.get(e?.operationId);return this.authorized(connectionId,e)&&Number.isInteger(e.sequence)&&e.sequence>0&&e.sequence<=r.sequence;}
 event(connectionId,e){const r=this.records.get(e?.operationId);if(!this.authorized(connectionId,e)||!Number.isInteger(e.sequence)||e.sequence!==r.sequence+1||r.settled)return false;const allowed=r.name==='import_variables'?['native-import','variable-read','collection-read','verified','settled']:r.name==='use_component'?['component-import','instance-created','attached','verified','settled']:['verified','settled'];if(!allowed.includes(e.stage))return false;if(r.name==='import_variables'&&e.key&&!r.variables.some(v=>v.key===e.key))return false;if(e.id){if(typeof e.id!=='string')return false;if(r.name==='import_variables'){if(!e.key)return false;r.variables.find(v=>v.key===e.key).id=e.id;}else r.resourceId=e.id;}r.lastConnectionId=connectionId;r.sequence=e.sequence;r.commandSent=true;if(e.stage!=='settled')r.stage=e.stage;if(e.stage==='verified')r.state='verified';if(e.stage==='settled'){r.settled=true;const complete=r.name==='import_variables'?r.stage==='verified'&&r.variables.every(v=>typeof v.id==='string'&&v.id.length>0):r.stage==='verified'&&typeof r.resourceId==='string';r.state=e.success?(complete?'verified':'unknown'):'failed';r.operationStatus=e.success?(complete?'applied':'unknown'):(e.operationStatus||'unknown');r.code=e.success&&!complete?'OPERATION_JOURNAL_INCOMPLETE':e.code||null;}this.save(r);return true;}
 mark(id,fields){const r=this.records.get(id);if(!r)return;return this.save(Object.assign(r,fields));}
}
